version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fluentflow-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: fluent_flow
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql # Otomatis jalankan script saat start

  pgadmin:
    image: dpage/pgadmin4
    container_name: fluentflow-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fluentflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Akses pgAdmin di http://localhost:5050
    depends_on:
      - db

volumes:
  postgres_data:
